### ISSUE TITLE
Notch support

### ISSUE THREAD

**Issue by lukasbash** [pedromassango/titled_navigation_bar#16] opened 2019-08-25 19:51 UTC
Would it be possible to support a notch?

**Comment by pedromassango** [comment] 2019-08-25 20:13
Yes

**Comment by pedromassango** [comment] 2020-04-23 20:16
Since this package was designed to be used as bottom navigation bar this enchancement is not a priority now. Please fell free to send a PR. I will close this for now

**Closed by pedromassango** 2020-04-23 20:16 UTC
Labels: enhancement
